name: Lint and Format

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run:  npm install
      - name: Lint and format
        run:  npm run lint && npm run format:check
